### ISSUE TITLE
TypeError: AocClient is not a constructor

### ISSUE THREAD

**Issue by dauc** [toblu/advent-of-code-client#1]
This is cool, thanks!  I had a small issue getting it to work with the examples from the readme.  I found that

```js
const AocClient = require('advent-of-code-client');

const client = new AocClient({
  year: 2020,
  day: 7,
  token: process.env.AOC_SESSION
});
```
resulted in the following error

```preformatted
const client = new AocClient({
               ^
TypeError: AocClient is not a constructor
```

It worked fine with `const client = new AocClient.AocClient({` ... 

Disclosure: I'm pretty new to JS and might not know what I'm doing.  :D

**Comment by toblu** [comment]
Thanks for the feedback!

You're right, there was an error in the readme. It's been fixed now in v0.1.2 :)
