### ISSUE TITLE
Puzzle input for day 10 of 2021 fails to load

### ISSUE THREAD

**Issue by bagley2014** [toblu/advent-of-code-client#6]
So I looked at the code a bit to see what was up with this particular day, and I noticed the regex in the following line:

https://github.com/toblu/advent-of-code-client/blob/6e4aa1c6e37c8046a852d4cf05446b6202a2a0e9/src/util/api.js#L69

The puzzle input in question happens to be filled with `<` and `>` so the regex matched and threw and error. 

I'm not sure what that check is supposed to be doing, so I don't know how to fix it. For the time being I just removed it from my local node_modules so I don't get any more false positives, but I figured I'd post here to make the issue known.

**Comment by toblu** [comment]
Thanks for reporting, I was not aware of this issue! I will take a look

**Comment by toblu** [comment]
Fixed in [v0.1.4](https://github.com/toblu/advent-of-code-client/releases/tag/v0.1.4)
